# -*- coding: utf-8 -*-
"""pipeline project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYHNvYLnKk02rLi_Z5eiPWZMGqCrBw0l
"""

import pandas as pd

data = {
    "OrderID": [101, 102, 103, 104, 105],
    "Product": ["Laptop", "Mouse", "Chair", "Table", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Furniture", "Furniture", "Electronics"],
    "Price": [50000, 500, None, 4000, 1200],
    "Quantity": [2, 5, 3, 2, None]
}

df = pd.DataFrame(data)

df

df.to_csv("sales_data.csv",index= False)
print("csv file created succesfully")

df=pd.read_csv("sales_data.csv")
print(df)

df.info()

df.isnull().sum()

df['Price'] = df['Price'].fillna(0)
df['Quantity'] = df['Quantity'].fillna(0)

df.isnull().sum()

df['Total Sales'] = df['Price'] * df["Quantity"]
df

total_revenue = df["Total Sales"].sum()

print("Total Revenue:", total_revenue)

df['Total Sales'].sum()

print('Average Sales:', df['Total Sales'].mean())

highest = df.loc[df['Total Sales'].idxmax()]
print(highest['Product'])

category_sales = df.groupby("Category")["Total Sales"].sum()

print(category_sales)

top_products = df.sort_values(
    by="Total Sales",
    ascending=False
)

print(top_products.head(3))

def extract_data():
    print("Hello")

extract_data()

import pandas as pd

def extract_data():
    data = {
        "OrderID": [101, 102, 103],
        "Product": ["Laptop", "Mouse", "Chair"],
        "Price": [50000, 500, None],
        "Quantity": [2, 5, 3]
    }
    return pd.DataFrame(data)

def transform_data(df):
    df["Price"] = df["Price"].fillna(0)
    df["Total Sales"] = df["Price"] * df["Quantity"]
    return df

def load_data(df):
    print(df)

df = extract_data()
df = transform_data(df)
load_data(df)

def load_data(df):
    df.to_csv("sales_report.csv", index=False)
    print("Report saved successfully")

df = extract_data()
df = transform_data(df)
load_data(df)

import pandas as pd

# Extract Step
def extract_data():

    try:
        data = {
            "OrderID": [101, 102, 103],
            "Product": ["Laptop", "Mouse", "Chair"],
            "Price": [50000, 500, None],
            "Quantity": [2, 5, 3]
        }

        df = pd.DataFrame(data)

        print("Data extracted successfully")

        return df

    except Exception as e:
        print("Extraction Error:", e)


# Validation Step
def validate_data(df):

    required_columns = [
        "OrderID",
        "Product",
        "Price",
        "Quantity"
    ]

    for col in required_columns:

        if col not in df.columns:
            print(col, "column is missing")
            return False

    print("Validation successful")
    return True


# Transform Step
def transform_data(df):

    try:

        df["Price"] = df["Price"].fillna(0)

        df["Quantity"] = df["Quantity"].fillna(0)

        df["Total Sales"] = df["Price"] * df["Quantity"]

        print("Data transformed successfully")

        return df

    except Exception as e:
        print("Transformation Error:", e)


# Load Step
def load_data(df):

    try:

        df.to_csv("sales_report.csv", index=False)

        print("Report saved successfully")

    except Exception as e:
        print("Loading Error:", e)


# Main ETL Flow

df = extract_data()

if validate_data(df):

    df = transform_data(df)

    load_data(df)

    print("\nFinal Data:")
    print(df)

import logging

logging.basicConfig(
    level=logging.INFO,
    force=True
)

logging.info("Data extracted successfully")
logging.info("Validation successful")
logging.info("Data transformed successfully")
logging.info("Report saved successfully")

import pandas as pd

data = {
    "OrderID": [101, 102, 103],
    "Product": ["Laptop", "Mouse", "Chair"],
    "Price": [50000, 500, None],
    "Quantity": [2, 5, 3]
}

df = pd.DataFrame(data)

df.to_csv("sales_data.csv", index=False)

print("sales_data.csv created successfully")

def extract_data():

    df = pd.read_csv("sales_data.csv")

    return df

def extract_data():

    df = pd.read_csv("sales_data.csv")

    return df

df = extract_data()

print(df)

df = pd.read_csv("sales_data.csv")

print(df)

df = extract_data()

if df is not None and validate_data(df):

    df = transform_data(df)

    if df is not None:
        load_data(df)

        print(df)

data = {
    "OrderID": [101, 102, 103, 104],
    "Product": ["Laptop", "Mouse", "Chair", "Keyboard"],
    "Category": ["Electronics", "Electronics", "Furniture", "Electronics"],
    "Price": [50000, 500, None, 1200],
    "Quantity": [2, 5, 3, 4]
}

df = pd.DataFrame(data)
df.to_csv("sales_data.csv", index=False)

required_columns = [
    "OrderID",
    "Product",
    "Category",
    "Price",
    "Quantity"
]

df = transform_data(df)
print("Total Revenue:", df["Total Sales"].sum())

print("Average Revenue:", df["Total Sales"].mean())

print("Top Selling Product:")

print(df.loc[df["Total Sales"].idxmax()])

category_sales = df.groupby("Category")["Total Sales"].sum()

print(category_sales)

df.to_excel("sales_report.xlsx", index=False)
print(df)

!pip install openpyxl

def load_data(df):

    df.to_csv("sales_report.csv", index=False)

    print("Report saved successfully")

def load_data(df):

    df.to_excel("sales_report.xlsx", index=False)

    print("Excel report saved successfully")

df.to_csv("sales_report.csv", index=False)

df.to_excel("sales_report.xlsx", index=False)

pd.read_csv("sales_data.csv")

pd.read_excel("sales_report.xlsx")

def load_data(df):

    try:
        df.to_csv("sales_report.csv", index=False)

        df.to_excel("sales_report.xlsx", index=False)

        print("Reports saved successfully")

    except Exception as e:
        print("Loading Error:", e)
load_data(df)

df = transform_data(df)

total_revenue = df["Total Sales"].sum()

print("Total Revenue:", total_revenue)

df["Total Sales"]

average_revenue = df["Total Sales"].mean()

print("Average Revenue:", average_revenue)

highest = df.loc[df["Total Sales"].idxmax()]

print(highest)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# 
# # Automation Data Processing Pipeline (ETL Project)
# 
# ## Project Overview
# This project is an ETL pipeline built using Python and Pandas.
# 
# ## Features
# - Extract data from CSV
# - Validate data
# - Transform data
# - Generate reports
# 
# ## Output
# - sales_report.csv
# - sales_report.xlsx

!cat README.md

from google.colab import files
files.download("README.md")

import os
print(os.listdir())

import pandas as pd

data = {
    "OrderID": [101, 102, 103],
    "Product": ["Laptop", "Mouse", "Chair"],
    "Price": [50000, 500, None],
    "Quantity": [2, 5, 3]
}

df = pd.DataFrame(data)

df.to_csv("sales_data.csv", index=False)

print("sales_data.csv created")

df = extract_data()

if df is not None and validate_data(df):

    df = transform_data(df)

    if df is not None:
        load_data(df)

        print(df)

print(extract_data)

print(os.listdir())

from google.colab import files

files.download("sales_report.csv")

from google.colab import files

files.download("sales_report.xlsx")

from google.colab import files

files.download("README.md")